version: '3.0'

services:
  nginx:
    image: nginx:1.23-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./passwd:/etc/nginx/passwd
      - ./conf.d:/etc/nginx/conf.d
      - ./Fridays:/web/fridays
      - ./PMO:/web/pmo
      - ./Fintechinmass:/web/fin